#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source fzf autocompletion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Customize to your needs...
alias upy='yarn global upgrade-interactive'
alias up='sudo yum update'
alias zap='sudo yum autoremove'
alias sha256='shasum -a 256'
alias v='code'
alias vv='code .'
alias f='find . -name'
alias ff='grep -nrw . -e'
alias y='yarn'
alias ya='yarn add'
alias yad='yarn add --dev'
alias yr='yarn remove'
alias yu='yarn upgrade-interactive'
alias ppy='python3 -m http.server'
alias z='vi ~/.zshrc'
alias l='ls'
alias l1='ls -1A'
alias ltr='ls -ltr'
alias cls='clear'
alias ft='cdf'
alias tf='pushdf'
alias -g C='| wc -l'
alias -g H='| head'
alias -g L="| less"
alias -g N="| /dev/null"
alias -g S='| sort'
alias -g G='| grep'
